### ISSUE TITLE
Menu Button in compact mode is laid on top of the drawer (wrong z-index?)

### ISSUE THREAD

**Issue by pshihn** [PolymerElements/paper-drawer-panel#55] opened 2015-06-10 10:00 UTC
The menu button in the following code (in narrow mode) shows up on top of the drawer header, when drawer is open. It does not happen if the menu button is not inside paper-toolbar but in a div. 
(Seen on chrome: Version 43.0.2357.8)

``` html
<paper-drawer-panel>
  <paper-header-panel drawer>
    <paper-toolbar>
      <div>Application</div>
    </paper-toolbar>
    <div> Drawer content... </div>
  </paper-header-panel>
  <paper-header-panel main>
    <paper-toolbar>
      <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
      <div>Title</div>
    </paper-toolbar>
    <div> Main content... </div>
  </paper-header-panel>
</paper-drawer-panel>
```

**Comment by blasten** [comment] 2015-06-10 19:06
The issue is confirmed.

**Comment by blasten** [comment] 2015-06-12 18:46
@pshihn This is fixed now in `paper-toolbar`. Can you update it via `bower update` ?

**Closed as completed by blasten** 2015-06-12 18:46 UTC
Labels: bug, needs move
